# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - closed
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make Gradle wrapper script executable
      run: |
          chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to Docker Hub
      run: echo ${{ secrets.SECRET_PASSWORD }} | docker login -u ${{ secrets.SECRET_ID }} --password-stdin

    - name: Set up Docker Buildx
      run: docker buildx create --use

    - name: Build and Push Docker Image with Buildx
      run: |
        docker buildx build -t kimkagyun/kdbe:latest .
        docker buildx build --push -t kimkagyun/kdbe:latest .

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SECRET_PEMKEY }}
        port: 22
        script: |
          sudo docker pull kimkagyun/kdbe:latest
          sudo docker stop kdbe
          sudo docker rm kdbe
          sudo docker run -d -p 80:8080 --name kdbe kimkagyun/kdbe:latest


